spring:
  data:
    mongodb:
      host: vmiss.shirakawatyu.top
      port: 27017
      database: anime
      username: root
      password: shirakawatyu
      authentication-database: admin
  codec:
    max-in-memory-size: 128MB

aadb:
  date-filepath: D:\IdeaProjects\AnimeAggregatedDatabase
