spring:
  data:
    mongodb:
      host:
      port: 27017
      database: anime
      username: root
      password:
      authentication-database: admin
  codec:
    max-in-memory-size: 128MB

aadb:
  date-filepath: D:\IdeaProjects\AnimeAggregatedDatabase
